version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: composable-documentation
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - ./static:/usr/local/bin/static
